In [ ]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder,OrdinalEncoder
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.compose import ColumnTransformer
import pandas as pd

In [ ]:
df=pd.read_csv('/content/economy.csv')
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955"

In [ ]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
df['date'].head()

0   2022-02-11
1   2022-02-11
2   2022-02-11
3   2022-02-11
4   2022-02-11
Name: date, dtype: datetime64[ns]

In [ ]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['day_of_week'] = df['date'].dt.dayofweek
df['day_of_year'] = df['date'].dt.dayofyear
df = df.drop(columns=['date'])
df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,year,month,day,day_of_week,day_of_year
0,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",2022,2,11,4,42
1,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",2022,2,11,4,42
2,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",2022,2,11,4,42
3,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",2022,2,11,4,42
4,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",2022,2,11,4,42

In [ ]:
import pandas as pd
import numpy as np

def convert_to_minutes(time_str):
    try:
        time_str = time_str.lower()
        if 'h' in time_str and 'm' in time_str:
            hours, minutes = map(int, time_str.replace('h', ' ').replace('m', '').split())
            total_minutes = hours * 60 + minutes
        elif 'h' in time_str:
            hours = int(time_str.replace('h', ''))
            total_minutes = hours * 60
        elif 'm' in time_str:
            minutes = int(time_str.replace('m', ''))
            total_minutes = minutes
        else:
            total_minutes = np.nan
        return total_minutes
    except (ValueError, AttributeError):
        return np.nan
df['time_taken'] = df['time_taken'].apply(convert_to_minutes)

In [ ]:
df['price'] = df['price'].str.replace(",", '')
df['price']=df['price'].astype(str).astype(int)

In [ ]:
df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,year,month,day,day_of_week,day_of_year
0,SpiceJet,SG,8709,18:55,Delhi,130.0,non-stop,21:05,Mumbai,5953,2022,2,11,4,42
1,SpiceJet,SG,8157,06:20,Delhi,140.0,non-stop,08:40,Mumbai,5953,2022,2,11,4,42
2,AirAsia,I5,764,04:25,Delhi,130.0,non-stop,06:35,Mumbai,5956,2022,2,11,4,42
3,Vistara,UK,995,10:20,Delhi,135.0,non-stop,12:35,Mumbai,5955,2022,2,11,4,42
4,Vistara,UK,963,08:50,Delhi,140.0,non-stop,11:10,Mumbai,5955,2022,2,11,4,42

In [ ]:
df.tail()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,year,month,day,day_of_week,day_of_year
206769,Vistara,UK,832,07:05,Chennai,830.0,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,7697,2022,3,31,3,90
206770,Vistara,UK,832,07:05,Chennai,830.0,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,7709,2022,3,31,3,90
206771,Vistara,UK,826,12:30,Chennai,1235.0,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,8640,2022,3,31,3,90
206772,Vistara,UK,822,09:45,Chennai,1400.0,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,8640,2022,3,31,3,90
206773,Vistara,UK,824,20:30,Chennai,1465.0,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,8640,2022,3,31,3,90

In [ ]:
df['stop'] = df['stop'].str.replace('\n', '').str.replace('\t', '')

In [ ]:
df.tail()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,year,month,day,day_of_week,day_of_year
206769,Vistara,UK,832,07:05,Chennai,830.0,1-stop,20:55,Hyderabad,7697,2022,3,31,3,90
206770,Vistara,UK,832,07:05,Chennai,830.0,1-stop,20:55,Hyderabad,7709,2022,3,31,3,90
206771,Vistara,UK,826,12:30,Chennai,1235.0,1-stop,09:05,Hyderabad,8640,2022,3,31,3,90
206772,Vistara,UK,822,09:45,Chennai,1400.0,1-stop,09:05,Hyderabad,8640,2022,3,31,3,90
206773,Vistara,UK,824,20:30,Chennai,1465.0,1-stop,20:55,Hyderabad,8640,2022,3,31,3,90

In [ ]:
df.isna().sum()

airline        0
ch_code        0
num_code       0
dep_time       0
from           0
time_taken     4
stop           0
arr_time       0
to             0
price          0
year           0
month          0
day            0
day_of_week    0
day_of_year    0
dtype: int64

In [ ]:
x=df.drop('price',axis=1)
y=df['price'].copy()

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_num=X_train.select_dtypes(include=np.number)
x_cat=X_train.select_dtypes(include='object')

In [ ]:
x_num_pipeline=Pipeline([
    ('scaler',StandardScaler()),
    ('imputer',SimpleImputer(strategy='most_frequent'))
])

x_cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
])
x_cat

,airline_Air India,airline_AirAsia,airline_GO FIRST,airline_Indigo,airline_SpiceJet,airline_StarAir,airline_Trujet,airline_Vistara,ch_code_2T,ch_code_6E,...,arr_time_23:45,arr_time_23:50,arr_time_23:55,arr_time_23:59,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165414,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
165415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
165416,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
165417,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
165418,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
x_num_cols=X_train.select_dtypes(include=np.number).columns
x_cat_cols=X_train.select_dtypes(include='object').columns

In [ ]:
transformer=ColumnTransformer([
    ("num",x_num_pipeline,x_num_cols),
    ("cat",x_cat_pipeline,x_cat_cols)
])
X_train_prepared=pd.DataFrame(transformer.fit_transform(X_train),columns=transformer.get_feature_names_out())
X_test_prepared=pd.DataFrame(transformer.transform(X_test),columns=transformer.get_feature_names_out())
X_test_prepared

,num__num_code,num__time_taken,num__year,num__month,num__day,num__day_of_week,num__day_of_year,cat__airline_Air India,cat__airline_AirAsia,cat__airline_GO FIRST,...,cat__arr_time_23:45,cat__arr_time_23:50,cat__arr_time_23:55,cat__arr_time_23:59,cat__to_Bangalore,cat__to_Chennai,cat__to_Delhi,cat__to_Hyderabad,cat__to_Kolkata,cat__to_Mumbai
0,-0.640784,-0.915303,0.0,0.702038,-0.664785,1.022575,0.285027,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,-0.324444,0.500753,0.0,-1.424425,0.568883,-0.976147,-1.045725,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-0.404176,-0.800176,0.0,0.702038,1.679185,0.023214,1.689710,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.427060,-1.295220,0.0,0.702038,0.322150,1.522256,0.876473,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,-0.348148,0.212937,0.0,0.702038,-0.911519,0.023214,0.137166,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41350,-0.419691,0.028735,0.0,0.702038,1.679185,0.023214,1.689710,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
41351,1.951564,-1.064967,0.0,0.702038,0.198783,1.022575,0.802542,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
41352,-0.417105,0.673443,0.0,0.702038,-1.775087,0.023214,-0.380349,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
41353,-0.360216,1.226050,0.0,0.702038,0.445517,-1.475828,0.950403,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
41354,-0.382196,-1.214632,0.0,0.702038,-0.418052,-1.475828,0.432889,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.isna().sum()

airline        0
ch_code        0
num_code       0
dep_time       0
from           0
time_taken     4
stop           0
arr_time       0
to             0
price          0
year           0
month          0
day            0
day_of_week    0
day_of_year    0
dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression
full_pipe=make_pipeline(transformer, LinearRegression())
full_pipe.fit(X_train,y_train)
full_pipe.score(X_test,y_test)

0.5897146864827341

In [ ]:
from sklearn.tree import DecisionTreeRegressor
full_pipeline=make_pipeline(transformer,DecisionTreeRegressor())
full_pipeline.fit(X_train,y_train)
full_pipeline.score(X_test,y_test)

0.8543359152081278

In [ ]:
from sklearn.ensemble import RandomForestRegressor
full_pipeline=make_pipeline(transformer,RandomForestRegressor())
full_pipeline.fit(X_train,y_train)
full_pipeline.score(X_test,y_test)

0.9119740940777424

In [ ]:
full_pipeline.predict(X_test.iloc[:10])

array([ 3800.54, 11377.  ,  5362.36,  2758.31,  3473.  ,  5684.59,
        3187.83,  1967.7 , 19414.  ,  9433.13])

In [ ]:
y_test.iloc[:10]

81260      3543
36726     11520
135553     5523
50358      2738
162314     3471
115574     5402
167752     3072
192282     1830
94392     22189
170093    10979
Name: price, dtype: int64

In [ ]:
from sklearn.model_selection import GridSearchCV
pipeline = Pipeline(steps=[('preprocessor', transformer),
                           ('classifier', RandomForestRegressor())])


param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 10, 20],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

best_model = grid_search.best_estimator_
test_accuracy = best_model.score(X_test, y_test)
print("Test accuracy:", test_accuracy)